[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "social_media_agent"
version = "0.0.1"
description = "Social media agent package"
authors = [{name = "You"}]
dependencies = []
